version: "3"

services:

  postgres:
    image: postgis/postgis:13-3.1-alpine
    command: postgres
    container_name: postgres_landing_page
    restart: always
    env_file:
      - .postgres.env
    ports:
      - "5442:5432"
    volumes:
      - .docker/data/postgres:/var/lib/postgresql/data
      - .docker/init/postgres/init_db/1_init_db.sh:/docker-entrypoint-initdb.d/1_init_db.sh